"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sqlite = exports.db = void 0;
var better_sqlite3_1 = require("better-sqlite3");
var dotenv = require("dotenv");
var better_sqlite3_2 = require("drizzle-orm/better-sqlite3");
dotenv.config();
var sqlite = new better_sqlite3_1.default(process.env.DB_URL);
exports.sqlite = sqlite;
var db = (0, better_sqlite3_2.drizzle)(sqlite);
exports.db = db;
